### ISSUE TITLE
Project, funder, dataProvider: Project and Agents tab

### ISSUE THREAD

**Issue by kmexter** [marco-bolo/dataset-catalogue#13]
First question:

We currently ask for 
data provider, data contact, data contributors, funders - the first two in the Description tab and the second two in the Ackowledgements 
I am thinking that this is too many. Should we remove Funder? 

Second question
We have a Project tab added by @pieterprovoost and there was a good reason that I have forgotten. My question however is, as we are now taking the approach of having all agents described in an Agent tab, we need to better explain why we are not doing that for Project. So Pieter, could you add a full description to the columns in the Project tab to explain what this is that, making it different from a data provider?

**Comment by kmexter** [comment]
FYI I have removed the column Funder, since I need to get this finished asap. We can add it back again later if people want it

**Comment by kmexter** [comment]
I dont want to add spatial and temporal scope to the agents tab - for most it will not be necessary information.
It is enough to just have a better description of what this is, that is not also the funder, the data provider, or the data contact. I know you did tell me something but I have forgotten it - you can also update that column description yourself.

**Comment by kmexter** [comment]
If we made the project MBO for all? That way, we can maybe use this to make an MBO "collection".

**Comment by pieterprovoost** [comment]
Good suggestion to add MBO as a project, but I think we need to allow multiple projects then so we can also support views on let's say ARMS or LifeWatch collections. Again, I'm happy to cover this with the Agents tab, if we can just add one more column for geographic scope. I'm insisting because we need project geographic scope for the GOOS BioEco portal.

**Comment by kmexter** [comment]
I really don't want to add any more to the agents tab: geographic scope simply does not fit in with the purpose of that tab. It is perfectly OK to have a Projects tab: all I need is an explanation to put in the googlesheet as to what this "project" is that makes it different to the funder, data provider, data contact. That way, people will know what to put in there (esp as for many, funder will be the same as project)

**Comment by kmexter** [comment]
Resolved: keeping the project tab, renaming it to programme, and providing this explanation: The programme or project in which your datasets were collected. To link the MBO data to the GOOS BioEcoPanel, it is necessary to gather information about biodiversity monitoring programmes, and this is what we want to collect here.
Enter each project relevant to your data on a separate row
